version: 2


sources:
  - name: gz_raw_data
    description: data from greenweez (french brand eco-responsible)
    tables:
      - name: raw_gz_sales
        description: sales of Greenweez / we have one row per product_id found in each orders_id
        columns:
           - name: date_date
             description: date of purchase
           - name: orders_id
             description: foreign key to ship
           - name: pdt_id
             description: foreign key to product
           - name: revenue
             description: the amount paid by the customer to purchase the product. revenue = quantity * selling_price
           - name: quantity
             description: the quantity of products purchased for a given order
      - name: raw_gz_product
        description: purchase price of products
        columns:
          - name: products_id
            description: primary key
            tests : 
                - unique
                - not_null
          - name: purchase_price
            description: price of the purchase
      - name: raw_gz_ship
        description: shipping costs
        columns:
          - name: orders_id
            description: number of the order
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: numerber of ship
          - name: log_cost
            description: price of the log
          - name: ship_cost
            description: price of the ship
        
        


          